data:
  colormode: RGB
  inference:
    normalize_images: true
  train:
    affine:
      p: 0.5
      rotation: 30
      scaling:
      - 1.0
      - 1.0
      translation: 0
    collate:
      type: ResizeFromDataSizeCollate
      min_scale: 0.4
      max_scale: 1.0
      min_short_side: 128
      max_short_side: 1152
      multiple_of: 32
      to_square: false
    covering: false
    gaussian_noise: 12.75
    hist_eq: false
    motion_blur: false
    normalize_images: true
device: auto
metadata:
  project_path: /storage/ice1/0/3/kcozart6/dlc_model-student-2023-07-26
  pose_config_path: 
    /storage/ice1/0/3/kcozart6/dlc_model-student-2023-07-26/dlc-models-pytorch/iteration-0/dlc_modelJul26-trainset95shuffle1/train/pose_cfg.yaml
  bodyparts:
  - nose
  - lefteye
  - righteye
  - spine1
  - spine2
  - spine3
  - backfin
  - leftfin
  - rightfin
  unique_bodyparts: []
  individuals:
  - fish1
  - fish2
  - fish3
  - fish4
  - fish5
  - fish6
  - fish7
  - fish8
  - fish9
  - fish10
  with_identity: false
method: bu
model:
  backbone:
    type: ResNet
    model_name: resnet50_gn
    output_stride: 16
    freeze_bn_stats: true
    freeze_bn_weights: false
  backbone_output_channels: 2048
  heads:
    bodypart:
      type: DLCRNetHead
      predictor:
        type: PartAffinityFieldPredictor
        num_animals: 10
        num_multibodyparts: 9
        num_uniquebodyparts: 0
        nms_radius: 5
        sigma: 1.0
        locref_stdev: 7.2801
        min_affinity: 0.05
        graph: &id001
        - - 0
          - 1
        - - 0
          - 2
        - - 0
          - 3
        - - 0
          - 4
        - - 0
          - 5
        - - 0
          - 6
        - - 0
          - 7
        - - 0
          - 8
        - - 1
          - 2
        - - 1
          - 3
        - - 1
          - 4
        - - 1
          - 5
        - - 1
          - 6
        - - 1
          - 7
        - - 1
          - 8
        - - 2
          - 3
        - - 2
          - 4
        - - 2
          - 5
        - - 2
          - 6
        - - 2
          - 7
        - - 2
          - 8
        - - 3
          - 4
        - - 3
          - 5
        - - 3
          - 6
        - - 3
          - 7
        - - 3
          - 8
        - - 4
          - 5
        - - 4
          - 6
        - - 4
          - 7
        - - 4
          - 8
        - - 5
          - 6
        - - 5
          - 7
        - - 5
          - 8
        - - 6
          - 7
        - - 6
          - 8
        - - 7
          - 8
        edges_to_keep:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
        - 18
        - 19
        - 20
        - 21
        - 22
        - 23
        - 24
        - 25
        - 26
        - 27
        - 28
        - 29
        - 30
        - 31
        - 32
        - 33
        - 34
        - 35
        apply_sigmoid: true
        clip_scores: false
      target_generator:
        type: SequentialGenerator
        generators:
        - type: HeatmapPlateauGenerator
          num_heatmaps: 9
          pos_dist_thresh: 17
          heatmap_mode: KEYPOINT
          gradient_masking: false
          generate_locref: true
          locref_std: 7.2801
        - type: PartAffinityFieldGenerator
          graph: *id001
          width: 20
      criterion:
        heatmap:
          type: WeightedBCECriterion
          weight: 1.0
        locref:
          type: WeightedHuberCriterion
          weight: 0.05
        paf:
          type: WeightedHuberCriterion
          weight: 0.1
      heatmap_config:
        channels:
        - 2048
        - 9
        kernel_size:
        - 3
        strides:
        - 2
      locref_config:
        channels:
        - 2048
        - 18
        kernel_size:
        - 3
        strides:
        - 2
      paf_config:
        channels:
        - 2048
        - 72
        kernel_size:
        - 3
        strides:
        - 2
      num_stages: 5
net_type: resnet_50
runner:
  type: PoseTrainingRunner
  gpus:
  key_metric: test.mAP
  key_metric_asc: true
  eval_interval: 10
  optimizer:
    type: AdamW
    params:
      lr: 0.0001
  scheduler:
    type: LRListScheduler
    params:
      lr_list:
      - - 1e-05
      - - 1e-06
      milestones:
      - 160
      - 190
  snapshots:
    max_snapshots: 5
    save_epochs: 25
    save_optimizer_state: false
train_settings:
  batch_size: 32
  dataloader_workers: 0
  dataloader_pin_memory: false
  display_iters: 500
  epochs: 150
  seed: 42
